apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/stu20-demo-frontend
  newName: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/stu20-demo-frontend
  newTag: e3a8e379
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
